<?php

/**
 *
 */
class PublizonProduct {
  private $created;
  private $modified;
  private $published;
  private $status;
  private $language;
  private $cover;
  private $teaser_link;
  private $isbn;
  private $contributors;
  private $formats;
  private $bytes;
  private $duration;
  private $price;
  private $publiser;
  private $description;
  private $categories;

  public function __construct() {}
}