<?php
/**
 * @file
 *
 */

/**
 * Implements hook_schema().
 */
function publizon_library_schema() {
  $schema = array();

  $schema['cache_publizon_library'] = drupal_get_schema_unprocessed('system', 'cache');

  return $schema;
}

/**
 * Implements hook_install().
 */
function publizon_library_install() {
  drupal_install_schema('publizon_library');
}

/**
 * Implements hook_uninstall().
 */
function publizon_library_uninstall() {
  drupal_uninstall_schema('publizon_library');
}