<?php
/**
 * @file
 * Defines the users loans blocks. It module also contains the PublizonLoans
 * class which is used to store information and communicate with Publizon about
 * user loans.
 */

/**
 * Implements hook_theme().
 */
function publizon_product_theme() {
  return array(
    'publizon_product' => array(
      'arguments' => array('product' => NULL, 'type' => 'default'),
      'template' => 'templates/publizon-product',
      'file' => 'publizon_product.theme.inc',
    ),
    'publizon_products_list' => array(
      'arguments' => array('products' => NULL, 'type' => 'default'),
      'template' => 'templates/publizon-products-list',
      'file' => 'publizon_product.theme.inc',
    ),
  );
}

/**
 * Implements hook_flush_caches().
 *
 * Ensures that all caches used by the module is flush on cache clear. The
 * module also comes with drush support for clearing these caches.
 *
 * @see publizon_product.drush.inc
 */
function publizon_product_flush_caches() {
  return array('cache_publizon_product');
}