<?php
/**
 * @file
 * Defines the users loans blocks. It module also contains the PublizonLoans
 * class which is used to store information and communicate with Publizon about
 * user loans.
 */

function publizon_product_theme() {
  return array();
}

/**
 * Implements hook_flush_caches().
 *
 * Ensures that all caches used by the module is flush on cache clear. The
 * module also comes with drush support for clearing these caches.
 *
 * @see publizon_product.drush.inc
 */
function publizon_product_flush_caches() {
  return array('cache_publizon_product');
}