<?php
/**
 * @file
 *
 */

/**
 * Implements hook_flush_caches().
 *
 * Ensures that all caches used by the module is flush on cache clear. The
 * module also comes with drush support for clearing these caches.
 *
 * @see publizon.drush.inc
 */
function publizon_flush_caches() {
  return array('cache_publizon_loans');
}

function publizon_loans_block_info() {

}

function publizon_loans_block_view($delta) {

}
